import streamlit as st

from ui.components.quality_badge import QualityBadge
from ui.components.chart import MiniChart


class StockCard:

    def __init__(self):

        self.badge = QualityBadge()
        self.chart = MiniChart()

    # ---------------------------------------------------

    def render(

        self,

        ticker,
        company,

        price,
        change,
        pct_change,

        trade,

        df

    ):

        with st.container(border=True):

            # ==========================================
            # Header
            # ==========================================

            col1, col2 = st.columns([5, 1])

            with col1:

                st.title(ticker)

                st.caption(company)

            with col2:

                st.button(
                    "★",
                    key=f"card_watch_{ticker}",
                    use_container_width=True
                )

            st.write("")

            # ==========================================
            # Price
            # ==========================================

            delta = f"{change:+.2f} ({pct_change:+.2f}%)"

            st.metric(

                label="Current Price",

                value=f"₹ {price:,.2f}",

                delta=delta

            )

            st.write("")

            # ==========================================
            # Quality Badge
            # ==========================================

            self.badge.render(
                trade["status"]
            )
            # ==========================================
            # Trade Score
            # ==========================================

            col1, col2 = st.columns(2)
            
            with col1:
            
                st.metric(
            
                    label="Trade Quality",
            
                    value=f"{trade['score']}/100"
            
                )
            
            with col2:
            
                st.metric(
            
                    label="Grade",
            
                    value=trade["grade"]
            
                )
            
            st.markdown(
            
                f"<h3 style='text-align:center;color:#FFD54F'>{trade['stars']}</h3>",
            
                unsafe_allow_html=True
            
            )
            
            st.divider()
            # ==========================================
            # Price Action
            # ==========================================
            
            st.divider()
            
            st.subheader("📈 Price Action")
            
            fig = self.chart.render(df)
            
            st.plotly_chart(
                fig,
                use_container_width=True,
                config={
                    "displayModeBar": False
                }
            )
            
            st.divider()
            # ==========================================
            # Decision Summary
            # ==========================================
            
            st.divider()
            
            st.subheader("📋 Decision Summary")
            
            labels = [
            
                ("📈 Trend", trade["evidence"][0]),
            
                ("🚀 Momentum", trade["evidence"][1]),
            
                ("⚖ Risk", trade["evidence"][2])
            
            ]
            
            for title, value in labels:
            
                st.info(
            
                    f"**{title}**\n\n{value}"
            
                )
            
            # ==========================================
            # Confidence & Direction
            # ==========================================
            
            st.divider()
            
            col1, col2 = st.columns(2)
            
            with col1:
            
                st.metric(
            
                    label="Confidence",
            
                    value=trade["confidence"]
            
                )
            
            with col2:
            
                st.metric(
            
                    label="Direction",
            
                    value=trade["direction"]
            
                )
            
            st.caption("Generated by Trade Decision Engine (TDE)")
                       
